import { ReactElement } from "react";
import {
  BsArrowLeftRight,
  BsBox,
  BsBraces,
  BsClock,
  BsClockHistory,
  BsCodeSlash,
  BsEye,
  BsFiletypeSvg,
  BsHash,
  BsKey,
  BsLink45Deg,
  BsMarkdown,
  BsPercent,
  BsPersonVcard,
  BsRegex,
  BsShieldCheck,
  BsShieldLock,
  BsStars,
  BsTextParagraph,
  BsTools,
} from "react-icons/bs";
import { SiJsonwebtokens } from "react-icons/si";
import {
  TbApi,
  TbArrowsExchange,
  TbBinary,
  TbBrandGraphql,
  TbBrandHtml5,
  TbBrandJavascript,
  TbDatabase,
  TbDeviceAnalytics,
  TbFileTypeCss,
  TbFileTypeHtml,
  TbFingerprint,
  TbNetwork,
  TbSchema,
  TbWorld,
  TbWorldSearch,
} from "react-icons/tb";

export interface ToolModule {
  id: string;
  name: string;
  description: string;
  icon: ReactElement;
  order: number;
}

export const tools = [
  {
    id: "jwt",
    path: "/jwt",
    icon: <SiJsonwebtokens />,
    text: "JWT Tools",
    description: "Securely decode, inspect, and verify JWTs in seconds",
    module: "security",
  },
  {
    id: "markdown",
    path: "/markdown",
    icon: <BsMarkdown />,
    text: "Markdown",
    description: "Write, preview, and export Markdown with live formatting",
    module: "viewers",
  },
  {
    id: "graphiql",
    path: "/graphiql",
    icon: <TbBrandGraphql />,
    text: "GraphiQL",
    description: "Explore schemas, run queries, and debug GraphQL responses",
    module: "network",
  },
  {
    id: "rest",
    path: "/rest",
    icon: <TbApi />,
    text: "REST Client",
    description: "Build, send, and debug HTTP requests with rich tooling",
    module: "network",
  },
  {
    id: "regex",
    path: "/regex",
    icon: <BsRegex />,
    text: "Regex Tester",
    description: "Craft, test, and visualize regular expressions interactively with highlights",
    module: "utilities",
  },
  {
    id: "cron",
    path: "/cron",
    icon: <BsClock />,
    text: "Cron",
    description: "Build, parse, and validate cron expressions with schedule previews",
    module: "utilities",
  },
  {
    id: "har-viewer",
    path: "/har-viewer",
    icon: <TbDeviceAnalytics />,
    text: "HAR Viewer",
    description: "Inspect performance, requests, and waterfalls from HAR files",
    module: "network",
  },
  {
    id: "dns",
    path: "/dns",
    icon: <TbWorldSearch />,
    text: "DNS Lookup",
    description: "Query multiple resolvers, DNSSEC, and reverse lookups",
    module: "network",
  },
  {
    id: "epoch",
    path: "/epoch",
    icon: <BsClockHistory />,
    text: "Epoch Converter",
    description: "Convert epoch timestamps to readable dates and timezones",
    module: "converters",
  },
  {
    id: "diff",
    path: "/diff",
    icon: <BsArrowLeftRight />,
    text: "Diff",
    description: "Compare text, JSON, XML, and code with Monaco diff",
    module: "viewers",
  },
  {
    id: "timezone",
    path: "/timezone",
    icon: <TbWorld />,
    text: "Timezone",
    description: "View multiple timezones with a scrubber and persistent preferences",
    module: "utilities",
  },
  {
    id: "ssh-keys",
    path: "/ssh-keys",
    icon: <BsShieldLock />,
    text: "SSH Keys",
    description: "Generate, validate, and copy SSH keys securely for servers",
    module: "security",
  },
  {
    id: "svg-preview",
    path: "/svg-preview",
    icon: <BsFiletypeSvg />,
    text: "SVG Preview",
    description: "Preview, inspect, and optimize SVGs with DOM and path details",
    module: "viewers",
  },
  {
    id: "bundlephobia",
    path: "/bundlephobia",
    icon: <BsBox />,
    text: "Bundle Analyzer",
    description: "Check npm package size, exports, and dependency impact",
    module: "utilities",
  },
  {
    id: "ids",
    path: "/ids",
    icon: <BsPersonVcard />,
    text: "ID Generator",
    description: "Create UUIDs, NanoIDs, and custom IDs for apps",
    module: "generators",
  },
  {
    id: "hmac",
    path: "/hmac",
    icon: <BsHash />,
    text: "HMAC Generator",
    description: "Compute HMAC signatures using Web Crypto",
    module: "security",
  },
  {
    id: "stateless-password",
    path: "/stateless-password",
    icon: <BsKey />,
    text: "Stateless Password",
    description: "Derive strong site passwords from one master password without storing it",
    module: "generators",
  },
  {
    id: "certificate-decoder",
    path: "/x509",
    icon: <BsShieldCheck />,
    text: "Certificate Decoder",
    description: "Decode X.509 certs and CSRs, view fields, extensions, fingerprints",
    module: "security",
  },
  {
    id: "url-parser",
    path: "/url-parser",
    icon: <BsLink45Deg />,
    text: "URL Parser",
    description: "Parse, edit, and validate URL components for debugging",
    module: "converters",
  },
  {
    id: "url-encoder",
    path: "/url-encoder",
    icon: <BsPercent />,
    text: "URL Encoder",
    description: "Encode, decode, and sanitize URLs for safe sharing",
    module: "converters",
  },
  {
    id: "json-formatter",
    path: "/json-formatter",
    icon: <BsBraces />,
    text: "JSON Formatter",
    description: "Format, minify, and explore JSON with a collapsible tree",
    module: "formatters",
  },
  {
    id: "escape",
    path: "/escape",
    icon: <BsCodeSlash />,
    text: "Backslash Escape",
    description: "Escape or unescape strings with backslash sequences",
    module: "converters",
  },
  {
    id: "base64",
    path: "/base64",
    icon: <TbBinary />,
    text: "Base64",
    description: "Encode and decode Base64 strings with a text area",
    module: "converters",
  },
  {
    id: "html-preview",
    path: "/html-preview",
    icon: <TbBrandHtml5 />,
    text: "HTML/CSS Preview",
    description: "Write, preview, and export HTML with live formatting",
    module: "viewers",
  },
  {
    id: "json-yaml",
    path: "/json-yaml",
    icon: <TbArrowsExchange />,
    text: "JSON/YAML",
    description: "Convert between JSON and YAML with a live preview",
    module: "converters",
  },
  {
    id: "hash",
    path: "/hash",
    icon: <TbFingerprint />,
    text: "Hashing Text",
    description: "Compute hashes of text with a live preview",
    module: "security",
  },
  {
    id: "quicktype",
    path: "/quicktype",
    icon: <TbSchema />,
    text: "QuickType",
    description: "Generate code from JSON with a live preview",
    module: "generators",
  },
  {
    id: "sql",
    path: "/sql",
    icon: <TbDatabase />,
    text: "SQL Formatter",
    description: "Format SQL queries with a live preview",
    module: "formatters",
  },
  {
    id: "css-minifier",
    path: "/css-minifier",
    icon: <TbFileTypeCss />,
    text: "CSS Minifier",
    description: "Minify CSS with a live preview",
    module: "formatters",
  },
  {
    id: "html-minifier",
    path: "/html-minifier",
    icon: <TbFileTypeHtml />,
    text: "HTML Minifier",
    description: "Minify HTML with a live preview",
    module: "formatters",
  },
  {
    id: "js-minifier",
    path: "/js-minifier",
    icon: <TbBrandJavascript />,
    text: "JS/TS Minifier",
    description: "Minify JS/TS with a live preview",
    module: "formatters",
  },
];

export const moduleRegistry: Record<string, ToolModule> = {
  network: {
    id: "network",
    name: "Network",
    description: "API development, testing, and network diagnostics",
    icon: <TbNetwork />,
    order: 1,
  },
  formatters: {
    id: "formatters",
    name: "Formatters",
    description: "Text manipulation, formatting, and code processing",
    icon: <BsTextParagraph />,
    order: 2,
  },
  security: {
    id: "security",
    name: "Security",
    description: "Security, authentication, and cryptographic utilities",
    icon: <BsShieldCheck />,
    order: 3,
  },
  converters: {
    id: "converters",
    name: "Converters",
    description: "Convert between different data formats and encodings",
    icon: <BsArrowLeftRight />,
    order: 4,
  },
  utilities: {
    id: "utilities",
    name: "Utilities",
    description: "Essential utilities for software development workflows",
    icon: <BsTools />,
    order: 5,
  },
  generators: {
    id: "generators",
    name: "Generators",
    description: "Generate content, data, and assets for development",
    icon: <BsStars />,
    order: 6,
  },
  viewers: {
    id: "viewers",
    name: "Viewers",
    description: "Preview, process, and manipulate files and media",
    icon: <BsEye />,
    order: 7,
  },
};
