import {
  BsBox,
  BsClock,
  BsClockHistory,
  BsFiletypeSvg,
  BsGlobe,
  BsMarkdown,
  BsPersonVcard,
  BsRegex,
  BsShieldLock,
} from "react-icons/bs";
import { SiJsonwebtokens } from "react-icons/si";
import { TbBrandGraphql } from "react-icons/tb";

export const tools = [
  {
    id: "jwt",
    path: "/jwt",
    icon: <SiJsonwebtokens />,
    text: "JWT Tools",
    description: "JWT encode, decode, verify",
  },
  {
    id: "markdown",
    path: "/markdown",
    icon: <BsMarkdown />,
    text: "Markdown",
    description: "Edit and preview Markdown",
  },
  {
    id: "graphiql",
    path: "/graphiql",
    icon: <TbBrandGraphql />,
    text: "GraphiQL",
    description: "GraphQL IDE and query tester",
  },
  {
    id: "rest",
    path: "/rest",
    icon: <BsGlobe />,
    text: "REST Client",
    description: "Send and debug HTTP requests",
  },
  {
    id: "regex",
    path: "/regex",
    icon: <BsRegex />,
    text: "Regex Tester",
    description: "Test and debug regex",
  },
  {
    id: "cron",
    path: "/cron",
    icon: <BsClock />,
    text: "Cron",
    description: "Build and parse cron jobs",
  },
  {
    id: "har-viewer",
    path: "/har-viewer",
    icon: <BsGlobe />,
    text: "HAR Viewer",
    description: "Analyze HAR network files",
  },
  {
    id: "epoch",
    path: "/epoch",
    icon: <BsClockHistory />,
    text: "Epoch Converter",
    description: "Convert timestamps and dates",
  },
  {
    id: "ssh-keys",
    path: "/ssh-keys",
    icon: <BsShieldLock />,
    text: "SSH Keys",
    description: "Generate and validate SSH keys",
  },
  {
    id: "svg-preview",
    path: "/svg-preview",
    icon: <BsFiletypeSvg />,
    text: "SVG Preview",
    description: "Preview and inspect SVG files",
  },
  {
    id: "bundlephobia",
    path: "/bundlephobia",
    icon: <BsBox />,
    text: "Bundle Analyzer",
    description: "Analyze npm package size",
  },
  {
    id: "ids",
    path: "/ids",
    icon: <BsPersonVcard />,
    text: "ID Generator",
    description: "Generate unique IDs",
  },
];
